services:

  backend:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
     - "8000:8000"
    command:
        - bash
        - -c
        - |
            poetry run python core/manage.py makemigrations
            poetry run python core/manage.py migrate
            poetry run python core/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env
    deploy:
      restart_policy:
        condition:  unless-stopped
        delay: 5s
    

  postgres:
    image: postgres:15.2-bullseye
    ports:
      - "5432:5432"
    env_file:
       - .env
    volumes:
      - backend_vol:/var/lib/postgresql/data

volumes:
  backend_vol:
